export const SET_CREDENTIAL_USERNAME = 'SET_CREDENTIAL_USERNAME';
export const RESET_CREDENTIALS = 'RESET_CREDENTIALS';
export const SET_CREDENTIAL_PASSWORD = 'SET_CREDENTIAL_PASSWORD';
export const SET_DATA_PENDING = 'SET_DATA_PENDING';
export const SET_DATA_SUCCESS = 'SET_DATA_SUCCESS';
export const SET_DATA_ERROR = 'SET_DATA_ERROR';
