export const SET_CREDENTIAL_USERNAME = 'SET_CREDENTIAL_USERNAME';
export const RESET_CREDENTIALS = 'RESET_CREDENTIALS';
export const SET_CREDENTIAL_PASSWORD = 'SET_CREDENTIAL_PASSWORD';
// export const RESET_CREDENTIAL_PASSWORD = 'RESET_CREDENTIAL_PASSWORD';
